apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/RawkodeAcademy/komodor-klustered
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: root-sync
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: flux-system
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: flux-system
  path: ./flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: drupal
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: default
  path: ./drupal
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
